#数据库连接
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/asong?useUnicode=true&characterEncoding=utf-8&useSSL=true&zeroDateTimeBehavior=convertToNull
    type: org.springframework.jdbc.datasource.DriverManagerDataSource
  #设置静态资源路径，多个以逗号分隔
  resources:
    static-locations: classpath:static/,file:static/
mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8080
fdfs:
  soTimeout: 1500
  connectTimeout: 600
  thumbImage:             #缩略图生成参数
    width: 150
    height: 150
  trackerList:            #TrackerList参数,支持多个
    - 120.24.253.38:22122

